"""empty message

Revision ID: 49395a1e405b
Revises: 
Create Date: 2021-11-09 12:54:25.741735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49395a1e405b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'parent', ['parent_id'])
    op.create_unique_constraint(None, 'student', ['student_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='unique')
    op.drop_constraint(None, 'parent', type_='unique')
    # ### end Alembic commands ###
